on:
  pull_request:
    types: [opened, reopened]

name: Pull Request Discord Notification
jobs:
  discordNotification:
    name: Discord Notification
    runs-on: ubuntu-latest
    steps:
      - uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        with:
            args: 'A new PR on {{ EVENT_PAYLOAD.repository.full_name }} is available\n{{EVENT_PAYLOAD.pull_request.html}}.'
